### ISSUE TITLE
Duplicated data

### ISSUE THREAD

**Issue by ponnou** [BuildSysUniformMetadata/GroundTruth#7] opened 2017-07-25 13:56 UTC
Hello,

I would like to report an issue with Brick.ttl, indeed we can see that some data are duplicated as shown below.

![image](https://user-images.githubusercontent.com/13155852/28575622-784e5056-711f-11e7-9a05-6dd3a0ff9159.png)

**Comment by jbkoh** [comment] 2017-07-25 18:36
It looks like this is caused by CO2_Sensor being a subclass of CO2_Sensor itself. I will fix it tonight. Thanks for the report!

**Comment by jbkoh** [comment] 2017-07-25 20:50
I am closing this issue after migrating this issue to the currently active repository.

**Closed as completed by jbkoh** 2017-07-25 20:50 UTC
